// <auto-generated />
using System;
using Loja.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Loja.Migrations
{
    [DbContext(typeof(LojaContext))]
    partial class LojaContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Loja.Models.Confeccao", b =>
                {
                    b.Property<int>("confeccaoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("data");

                    b.Property<int>("tipoProdutoId");

                    b.HasKey("confeccaoId");

                    b.HasIndex("tipoProdutoId");

                    b.ToTable("Confeccao");
                });

            modelBuilder.Entity("Loja.Models.TipoProduto", b =>
                {
                    b.Property<int>("tipoProdutoId")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("nome");

                    b.Property<int>("qtd");

                    b.HasKey("tipoProdutoId");

                    b.ToTable("TipoProduto");
                });

            modelBuilder.Entity("Loja.Models.Confeccao", b =>
                {
                    b.HasOne("Loja.Models.TipoProduto", "tipoProduto")
                        .WithMany()
                        .HasForeignKey("tipoProdutoId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
